### ISSUE TITLE
KeyError: 'metadata' for deleted Stripe customers

### ISSUE THREAD

**Issue by technolion** [jonaswitt/stripe-datev-exporter#19]
For most months the tool works perfectly and without error. However running it for some months returns this error:

```
(venv) tom@spix-2 stripe-datev-exporter % python3.9 stripe-datev-cli.py download 2024 7
Retrieving data between 2024-07-01 and 2024-07-31 (inclusive, Europe/Berlin)
Retrieved 12 invoice(s), total 21.42 EUR
Traceback (most recent call last):
  File "/Users/tom/Development/stripe-datev-exporter/venv/lib/python3.9/site-packages/stripe/stripe_object.py", line 90, in __getattr__
    return self[k]
  File "/Users/tom/Development/stripe-datev-exporter/venv/lib/python3.9/site-packages/stripe/stripe_object.py", line 132, in __getitem__
    raise err
  File "/Users/tom/Development/stripe-datev-exporter/venv/lib/python3.9/site-packages/stripe/stripe_object.py", line 120, in __getitem__
    return super(StripeObject, self).__getitem__(k)
KeyError: 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tom/Development/stripe-datev-exporter/stripe-datev-cli.py", line 268, in <module>
    StripeDatevCli().run(sys.argv)
  File "/Users/tom/Development/stripe-datev-exporter/stripe-datev-cli.py", line 52, in run
    getattr(self, args.command)(argv[2:])
  File "/Users/tom/Development/stripe-datev-exporter/stripe-datev-cli.py", line 82, in download
    revenue_items = stripe_datev.invoices.createRevenueItems(invoices)
  File "/Users/tom/Development/stripe-datev-exporter/stripe_datev/invoices.py", line 133, in createRevenueItems
    accounting_props = customer.getAccountingProps(cus, invoice=invoice)
  File "/Users/tom/Development/stripe-datev-exporter/stripe_datev/customer.py", line 86, in getAccountingProps
    if not customer.metadata.get("accountNumber", None):
  File "/Users/tom/Development/stripe-datev-exporter/venv/lib/python3.9/site-packages/stripe/stripe_object.py", line 92, in __getattr__
    raise AttributeError(*err.args)
AttributeError: metadata
(venv) tom@spix-2 stripe-datev-exporter % 
```

Some customers don't seem to have metadata. Do you think this could be improved in your code, or is it a problem in my Stripe setup?

**Comment by technolion** [comment]
Oh, I just found out, that this happens for customers who have been deleted on Stripe.

In our scenario we have a self-managed solutions, where users on a free plan can choose to switch to a paid plan using Stripe checkout. If they later choose to cancel their plan, the stripe customer is deleted. 

It would be great if stripe-datev-exporter can deal with deleted customers, as they might have generated revenue in the past before they got deleted.

**Comment by jonaswitt** [comment]
I'm not sure that supporting deleted customers is possible. As you can see from the error above, no metadata is returned by the Stripe API for deleted customers, and that would be one precondition for this tool to work (to get the customer's account number). I would not recommend deleting customers if you wish to access all historical information for bookkeeping purposes.

**Comment by technolion** [comment]
@jonaswitt I fixed this in my fork with some null checks:
https://github.com/technolion/stripe-datev-exporter/commit/f6e822f7641a56ceca864e008126f5726fee0672

Maybe you find this useful for your repo.

**Comment by jonaswitt** [comment]
Thanks for letting me know. I think this a conscious decision that users of this tool will have to make - simply skipping a legitimate transaction because the Stripe user is deleted may not be correct from the company's bookkeeping perspective. I would rather have an exception in this case. But there are a handful of good forks where people have made adjustments to their requirements, and it's great to have your fork too so people can get inspired. I'm not at a point where I have the resources to make all this configurable in the main fork unfortunately.
