### ISSUE TITLE
AssertionError when downloading data

### ISSUE THREAD

**Issue by technolion** [jonaswitt/stripe-datev-exporter#4]
First of all, thanks for the awesome tool!

I can download the data for all months of the previous year 2022 except for November. For this single month I get the following error:

```
(venv) porcupine:stripe-datev-exporter tom$ python stripe-datev-cli.py download 2022 11
Retrieving data between 2022-11-01 and 2022-11-30
Retrieved 6 invoice(s), total -66.94 EUR
Retrieved 2 charge(s), total 21.42 EUR
Wrote    6 invoices      to out/overview/overview-2022-11.csv
Wrote    6 revenue items to out/monthly_recognition/monthly_recognition-2022-11.csv
Traceback (most recent call last):
  File "/Users/tom/Development/stripe-datev-exporter/stripe-datev-cli.py", line 249, in <module>
    StripeDatevCli().run(sys.argv)
  File "/Users/tom/Development/stripe-datev-exporter/stripe-datev-cli.py", line 49, in run
    getattr(self, args.command)(argv[2:])
  File "/Users/tom/Development/stripe-datev-exporter/stripe-datev-cli.py", line 105, in download
    records += stripe_datev.invoices.createAccountingRecords(revenue_item)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/Development/stripe-datev-exporter/stripe_datev/invoices.py", line 287, in createAccountingRecords
    months = recognition.split_months(recognition_start, recognition_end, [amount_with_tax])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tom/Development/stripe-datev-exporter/stripe_datev/recognition.py", line 46, in split_months
    assert amount == sum(month["amounts"][idx] for month in months)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
(venv) porcupine:stripe-datev-exporter tom$ 
```

I am happy to provide more info in order to debug the problem, should that be necessary.

**Comment by technolion** [comment]
![Bildschirmfoto 2023-10-13 um 12 53 22](https://github.com/jonaswitt/stripe-datev-exporter/assets/1611505/e4095f61-7345-4385-9153-d0e91ebe0b9a)

**Comment by technolion** [comment]
I think the problem is due to the fact that in November '22 there was a refund for a customer that lead to a "negative payment" in Stripe.
This somehow makes the assertion `assert amount == sum(month["amounts"][idx] for month in months)` fail.
Commenting out the assertion allowed me to download the November data as a workaround.

**Comment by jonaswitt** [comment]
Thanks for the problem report! I wouldn't recommend commenting out the assertion. It looks like the statement before, doing a simple cosmetical improvement and avoiding 0 amounts, did not work well for negative total amounts. Check out #5 and see if that works better for you. You will miss one month of revenue recognition without the fix; if that is relevant to you at all.

**Comment by technolion** [comment]
#5 works perfectly for me:

```
(venv) porcupine:stripe-datev-exporter tom$ python3 stripe-datev-cli.py download 2022 11
Retrieving data between 2022-11-01 and 2022-11-30
Retrieved 6 invoice(s), total -66.94 EUR
Retrieved 2 charge(s), total 21.42 EUR
Wrote    6 invoices      to out/overview/overview-2022-11.csv
Wrote    6 revenue items to out/monthly_recognition/monthly_recognition-2022-11.csv
Wrote    4 acc. records  to out/datev/EXTF_2022-11_Revenue.csv
Wrote    2 acc. records  to out/datev/EXTF_2022-12_Revenue_From_2022-11.csv
Wrote    4 acc. records  to out/datev/EXTF_2022-11_Charges.csv
Retrieved 0 transfer(s), total 0 EUR
Retrieved 2 payout(s), total 20.57 EUR
Wrote    2 acc. records  to out/datev/EXTF_2022-11_Payouts.csv
Retrieved 0 contribution(s), total 0 EUR
(venv) porcupine:stripe-datev-exporter tom$
```

Thanks a lot!
